# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)
ps_ip: 129.104.254.40

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips:
    - 129.104.254.32:[3]
    - 129.104.254.33:[3]
    - 129.104.254.34:[3]
    - 129.104.254.35:[3]
    - 129.104.254.36:[3]
    - 129.104.254.37:[3]
    - 129.104.254.38:[3]
    - 129.104.254.39:[3]
    - 129.104.254.40:[2]

exp_path: /users/eleves-a/2024/baptiste.geisenberger/FedScale/fedscale/cloud

# Entry function of executor and aggregator under $exp_path
executor_entry: execution/executor.py

aggregator_entry: aggregation/aggregator.py

auth:
    ssh_user: "baptiste.geisenberger"
    ssh_private_key: "/users/eleves-a/2024/baptiste.geisenberger/.ssh/id_rsa"

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - source /Data/baptiste.geisenberger/miniconda3/bin/activate fedscale

# ========== Additional job configuration ========== 
# Default parameters are specified in config_parser.py, wherein more description of the parameter can be found

job_conf:
    - job_name: openimage_oort
    - num_classes: 596
    - task: cv
    - log_path: /users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark
    - data_set: openImg
    - data_dir: /Data/baptiste.geisenberger/Data/openImg
    - data_map_file: /Data/baptiste.geisenberger/Data/openImg/client_data_mapping/train.csv
    - clients_file: /users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark/dataset/data/clients.pkl
    - use_cuda: True
    - num_loaders: 2
    - clock_factor: 30
    - checkpoint_interval: 30
    # - resume_from: "/users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark/logs/openimage/ /checkpoints"

    - model: shufflenet_v2_x2_0
    - openimg_size: 256
    - gradient_policy: fed-prox
    - proxy_mu: 0.001

    - num_participants: 100
    - eval_interval: 5
    - rounds: 500
    - local_steps: 20
    - batch_size: 20
    - filter_less: 20
    - learning_rate: 0.04
    - decay_factor: 0.98
    - decay_round: 10
    - weight_decay: 4e-5
    - test_bsz: 20
    - overcommitment: 1.3

    - sample_mode: oort
    - pacer_step: 20
    - pacer_delta: 10
    - exploration_factor: 0.9
    - exploration_decay: 0.98
    - exploration_min: 0.2
    - round_penalty: 2.0
    - round_threshold: 10
    - blacklist_rounds: -1
    - t_budget: 120
