# Configuration file of FAR training experiment

# ========== Cluster configuration ========== 
# ip address of the parameter server (need 1 GPU process)
ps_ip: 129.104.253.51

# ip address of each worker:# of available gpus process on each gpu in this node
# Note that if we collocate ps and worker on same GPU, then we need to decrease this number of available processes on that GPU by 1
# E.g., master node has 4 available processes, then 1 for the ps, and worker should be set to: worker:3
worker_ips: 
    - 129.104.253.51:[3]
    - 129.104.252.56:[4]
    - 129.104.252.38:[4]


exp_path: /users/eleves-a/2024/baptiste.geisenberger/FedScale/fedscale/cloud

# Entry function of executor and aggregator under $exp_path
executor_entry: execution/executor.py

aggregator_entry: aggregation/aggregator.py

auth:
    ssh_user: "baptiste.geisenberger"
    ssh_private_key: "/users/eleves-a/2024/baptiste.geisenberger/.ssh/id_rsa"

# cmd to run before we can indeed run FAR (in order)
setup_commands:
    - source /Data/baptiste.geisenberger/miniconda3/bin/activate fedscale
#    - export NCCL_SOCKET_IFNAME='enp0s31f6'         # Run "ifconfig" to ensure the right NIC for nccl if you have multiple NICs

# ========== Additional job configuration ========== 
# Default parameters are specified in config_parser.py, wherein more description of the parameter can be found

job_conf:
    - job_name: google_speech
    - num_classes: 35
    - task: speech
    - log_path: /users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark
    - data_set: google_speech
    - data_dir: /Data/baptiste.geisenberger/Data/google_speech
    - data_map_file: /Data/baptiste.geisenberger/Data/google_speech/client_data_mapping/train.csv
    - clients_file: /users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark/dataset/data/clients.pkl
    - use_cuda: True
    - num_loaders: 2
    - clock_factor: 30
    - checkpoint_interval: 30
    - resume_from: "/users/eleves-a/2024/baptiste.geisenberger/FedScale/benchmark/logs/google_speech/ /checkpoints"

    - model: resnet34
    - gradient_policy: fed-prox
    - proxy_mu: 0.001

    - num_participants: 100
    - eval_interval: 5
    - rounds: 500
    - local_steps: 30
    - batch_size: 16
    - filter_less: 17
    - learning_rate: 0.02
    - decay_factor: 0.9
    - decay_round: 10
    - weight_decay: 8e-5
    - test_bsz: 20
    - overcommitment: 1.1

    - sample_mode: bliss
    - number_clients_to_refresh_utility: 500
    - number_clients_to_predict_utility: 500
    - amount_clients_predict_train_set: 1000
    - amount_clients_refresh_train_set: 1500
    - ema_alpha: 0.9
    - adaptive_training: True
    - run_phase_2: False
    - t_budget: 358
    - pacer_step: 20
    - pacer_delta: 10

    - g_model: xgboost
    - xgboost_g_n_estimators: 200
    - xgboost_g_learning_rate: 0.02
    - xgboost_g_max_depth: 6
    - xgboost_g_subsample: 0.7
    - xgboost_g_colsample_bytree: 0.7

    - h_model: xgboost
    - xgboost_h_n_estimators: 200
    - xgboost_h_learning_rate: 0.05
    - xgboost_h_max_depth: 3
    - xgboost_h_subsample: 0.7
    - xgboost_h_colsample_bytree: 1.0
